---
- hosts: lamp.ru
  debugger: on_failed
  become: true
  tasks:

- name: install zabbix package centos
    yum:
      name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-latest.el7.noarch.rpm
      state: present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: install zabbix package
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu20.04_all.deb
      when: ansible_distribution == 'ubuntu'

- name: Install zabbix-agent on ubuntu
    apt:
        name=zabbix-agent
        state=present

- name: change server_ip
    lineinfile:
      path: /etc/zabbix/zabbix_agent.conf
          regexp: 'Server=127.0.0.1'
          line: "Server=127.0.0.1,10.131.0.9"

- name: Start zabbix-agent
    service:
      name: zabbix-agent
      state: started
      enabled: yes
