---
- name: Nginx install on server fwubuntu2
  hosts: fwubuntu2.com
  become: yes
  tasks:

    - name: Install nginx ubuntu
      package:
        name: nginx
        state: latest
 
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
