---
- name: Install Zabbix agent
  become: yes
  hosts: fwubuntu2.com fwredhat.com
  debugger: on_failed
  tasks:

    - name: Install zabbix-release CentOS 7
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-latest.el7.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"


    - name: Install zabbix release package
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu20.04_all.deb
      when: ansible_distribution == 'Ubuntu'


    - name: Install zabbix-agent package
      package:
        name: zabbix-agent
        state: present


    - name: Change Server IP CentOS 7
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server='
        line: "Server=172.16.0.1"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"


    - name: Change Server IP Ubuntu
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server='
        line: "Server=172.16.0.1"
      when: ansible_distribution == 'Ubuntu'


    - name: Change Hostname Ubuntu
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '# Hostname='
        line: "Hostname={{ ansible_hostname }}"
      when: ansible_distribution == 'Ubuntu'

    - name: Change ServerActive IP CentOS 7
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'ServerActive='
        line: "ServerActive=172.16.0.1:10051"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Change Hostname CentOS 7
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Hostname=Zabbix server'
        line: "Hostname={{ ansible_hostname }}"  
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"


    - name: Change ServerActive IP Ubuntu
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'ServerActive='
        line: "ServerActive=172.16.0.1:10051"
      when: ansible_distribution == 'Ubuntu'

    - name: Stop zabbix-agent
      service:
        name: zabbix-agent
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Start zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes
